apiVersion: apps/v1
kind: Deployment
metadata:
  name: snmp_poller
  labels:
    app: flaskapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskapi
  template:
    metadata:
      labels:
        app: flaskapi
    spec:
      containers:
        - name: flaskapi
          image: jlalmenanza/snmp_poller_server
          ports:
            - containerPort: 4047
          env:
            - name: db_username
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: db_username
            - name: db_password
              valueFrom:
                secretKeyRef:
                  name: flaskapi-secrets
                  key: db_password
            - name: db_name
              value: flaskapi_demo